version: '3.3'
services:
  backend:
    build:
      context: ./
    ports: 
      - "3005:3000"
    environment: 
      PORT: 3000 
    networks:
      - fd_net  
    volumes: 
      - ./:/server:ro  
    depends_on: 
      - fd_mongo     

  fd_mongo:
    image: mongo:6.0.2
    restart: always
    networks:
      - fd_net
    volumes: 
      - /home/elena/Documents/mongo_backup/:/data/db

networks:
  fd_net:
